name: Sync ReadMe OpenAPI

on:
  push:
    branches: ["v1.0"]   # or main, whichever you use
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload OpenAPI spec
        uses: readmeio/rdme@v10
        with:
          rdme: openapi upload reference/API/openapi.yaml --key=${{ secrets.README_API_KEY }}

